name: MMOCoreAstra
version: '${project.version}'
author: Pry
website: github.com/Pryzinho
main: br.pry.mcoreaddon.CompatMain
depend:
  - MMOCore
api-version: '1.20'
commands:
  rpgst:
    description: Unlock a skill-tree ability.
